Commerce/urls.py
from django.conf.urls import url
from django.contrib import admin

from core import views

urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^contato$', views.contact,name='contact'),
    url(r'^produto$', views.product,name='product'),
    url(r'^produtos$', views.product_list,name='products'),
    url(r'^admin/', admin.site.urls),
]

catalog/models.py
from django.db import models


# Create your models here.

class Category(models.Model):
    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['name']

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)
    category = models.ForeignKey('catalog.Category', verbose_name='categoria', blank=True)
    description = models.TextField('Descrição', blank=True)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering = ['name']

    def __str__(self):
        return self.name

core/models.py
from django.db import models

# Create your models here.

catalog/views.py
#codding=utf-8

core/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def index(request):
    return render(request, 'index.html')


def contact(request):
    return render(request, 'contact.html')


def product_list(request):
    return render(request, 'product_list.html')


def product(request):
    return render(request, 'product.html')

core/templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>{% block title %}Django E-Commerce{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}" media="screen" />
	<link rel="stylesheet" href="{% static 'assets/custom.min.css' %}" media="screen" />
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="" class="navbar-brand">Django E-Commerce</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <a href="{% url 'index' %}">Início</a>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="download">Categorias <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="download">
                  {% for category in categories %}
                <li><a href="{%url 'products' %}">{{category.name}}</a></li>
                  {% endfor %}
              </ul>
            </li>
			<li>
				<a href="{% url 'contact'%}">Contato</a>
			</li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Minha Conta</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="container">
        {% block container %}{% endblock %}
		<footer>
			<div class="row">
			  <div class="col-lg-12">
			    <ul class="list-unstyled">
			      <li class="pull-right"><a href="#top">Voltar ao Topo</a></li>
			      <li><a href="">Início</a></li>
			      <li><a href="">Produtos</a></li>
			      <li><a href="">Contato</a></li>
			      <li><a href="">Termos e Privacidade</a></li>
			    </ul>
			  </div>
			</div>
		</footer>
	</div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'assets/bootstrap.min.js' %}"></script>
</body>
</html>

core/templates/contact.html
{% extends "base.html" %}
{% block title %}
Contato| {{block.super}}
{% endblock %}
{% block container%}
<div class="page-header">
    <h1>Fale conosco</h1>
    <form class="form-horizontal">
        <fieldset>
            <div class="form-group">
                <label for="id_name" class="col-md-3 control-label">Nome</label>
                <div class="col-md-9">
                    <input type="text" class="form-control" id="id_name" placeholder="Nome"/>
                </div>
            </div>
            <div class="form-group">
                <label for="id_email" class="col-md-3 control-label">E-mail</label>
                <div class="col-md-9">
                    <input type="text" class="form-control" id="id_email" placeholder="E-mail"/>
                </div>
            </div>
            <div class="form-group has-error">
                <label for="id_message" class="col-md-3 control-label">Mensagem</label>
                <div class="col-md-9">
                    <textarea class="form-control" rows="3" id="id_message"></textarea>
                    <span class="help-block">Este campo é obrigatório</span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </div>
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}

core/templates/index.html
{% extends "base.html" %}
{% block container %}
<div class="jumbotron page-header">
    <h1>Django E-Commerce</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore
        magna aliqua.</p>
    <p><a class="btn btn-primary">Saiba mais</a></p>
</div>
{% endblock %}

core/templates/product.html
{% extends "base.html" %}
{% block title %}
Produto | {{block.super}}
{% endblock %}
{% block container%}
<div class="page-header">
    <h1>Página do Produto</h1>
</div>
<div class="row">
    <div class="col-sm-4">
        <a href="#" class="thumbnail">
            <img src="http://placehold.it/350x250" alt=""/>
        </a>
    </div>
    <div class="col-sm-8">
        <dl>
            <dt>Lorem ipsum:</dt>
            <dd>Lorem ipsum dolor sit amet</dd>
            <dt>Lorem ipsum:</dt>
            <dd>Lorem ipsum dolor sit amet</dd>
            <dt>Lorem ipsum:</dt>
            <dd>Lorem ipsum dolor sit amet</dd>
            <dt>Lorem ipsum:</dt>
            <dd>Lorem ipsum dolor sit amet</dd>
            <dt>Lorem ipsum:</dt>
            <dd>Lorem ipsum dolor sit amet</dd>
        </dl>
    </div>
</div>
</div>
{% endblock %}

core/templates/product_list.html
{% extends "base.html" %}
{% block title %}
Produtos | {{block.super}}
{% endblock %}
{% block container%}
<div class="page-header">
    <h1>Produtos</h1>
</div>
<div class="row">
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <a href="#">
                <img src="http://placehold.it/350x250" alt=""/>
            </a>
            <div class="caption">
                <h3>Lorem ipsum dolor sit amet</h3>
                <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est
                    laborum.</p>
                <p><a href="#" class="btn btn-success" role="button">Button</a> <a href="#" class="btn btn-default"
                                                                                   role="button">Button</a></p>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <a href="#">
                <img src="http://placehold.it/350x250" alt=""/>
            </a>
            <div class="caption">
                <h3>Lorem ipsum dolor sit amet</h3>
                <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est
                    laborum.</p>
                <p><a href="#" class="btn btn-success" role="button">Button</a> <a href="#" class="btn btn-default"
                                                                                   role="button">Button</a></p>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <a href="#">
                <img src="http://placehold.it/350x250" alt=""/>
            </a>
            <div class="caption">
                <h3>Lorem ipsum dolor sit amet</h3>
                <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est
                    laborum.</p>
                <p><a href="#" class="btn btn-success" role="button">Button</a> <a href="#" class="btn btn-default"
                                                                                   role="button">Button</a></p>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

core/templates/x.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Django E-Commerce</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<link rel="stylesheet" href="assets/bootstrap.min.css" media="screen" />
	<link rel="stylesheet" href="assets/custom.min.css" media="screen" />
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="" class="navbar-brand">Django E-Commerce</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <a href="#">Início</a>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="download">Categorias <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="download">
                <li><a href="">Notebooks</a></li>
				<li><a href="">Acessórios</a></li>
				<li><a href="">Celulares</a></li>
              </ul>
            </li>
			<li>
				<a href="contact.html">Contato</a>
			</li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Minha Conta</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="container">

	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="assets/bootstrap.min.js"></script>
</body>
</html>